server:
  port: 80
google:
  maps:
    key: ${GOOGLE_MAPS_KEY}
okta:
  oauth2:
    issuer: https://login.clines.de/oauth2/default
    audience: api://default
spring:
  cloud:
    stream:
      bindings:
        input:
          destination: place-requests
        output:
          destination: place-replies
management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true