apiVersion: v1
kind: Service
metadata:
  name: documentation
  labels:
    app: documentation
spec:
  selector:
    app: documentation
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: NodePort